spring.application.name=employee-management-system

## --------------------------------------------
## Supabase Database Configuration
## --------------------------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

java.net.preferIPv4Stack=true

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.jdbc=DEBUG


## --------------------------------------------
## Security / JWT Configuration
## --------------------------------------------
application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=${JWT_EXPIRATION}


## --------------------------------------------
## Logging Configuration
## --------------------------------------------
logging.file.name=logs/employee-management-system.log
logging.level.root=INFO
logging.level.com.github.venkyslm.employee_management_system=DEBUG